Menu
Smart-Chef-Dev/sc-actions-client pull request #56
Opened 2021-05-18 21:01 UTC by roobel2005

2021-05-31 12:29 UTC, pkarpovich commented
move photos to backend 
https://docs.nestjs.com/recipes/serve-static#serve-static

2021-06-11 22:29 UTC, pkarpovich requested changes

2021-06-11 22:29 UTC, pkarpovich commented on src/components/MenuLayout.js
> +    width: 100%;
use properties from Flex component

2021-06-11 22:29 UTC, pkarpovich commented on src/components/MenuLayout.js
> +        <Flex height={1} flex={1} width={1} justifyContent="space-around">
try to reuse the simple layout component. Just add property 'needMenu'

2021-06-11 22:29 UTC, pkarpovich commented on src/components/divider.js
> +  width: 300%;
300?

2021-06-11 22:29 UTC, pkarpovich commented on src/components/h1.js
> +  margin-top: ${(props) => props.marginTop ?? "0.67em"};
0.7

2021-06-11 22:29 UTC, pkarpovich commented on src/components/h2.js
> +  padding: ${(props) => props.padding ?? props.p ?? "0"};
Do you really need all these properties in that component?

2021-06-11 22:29 UTC, pkarpovich commented on src/components/img.js
> +  width: ${(props) => (props.width ? `${100 * props.width}%` : "auto")};
same as above

2021-06-11 22:29 UTC, pkarpovich commented on src/components/label.js
> +  padding: ${(props) => props.padding ?? props.p ?? "0"};
same as above

2021-06-11 22:29 UTC, pkarpovich commented on src/components/menu-tabs/icon_basket.svg
> +<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
move it into assets icon folder

2021-06-11 22:29 UTC, pkarpovich commented on src/components/menu-tabs/icon_basket_dedicated.svg
> +<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
same as above

2021-06-11 22:29 UTC, pkarpovich commented on src/components/menu-tabs/icon_menu.svg
> +<svg width="24" height="25" viewBox="0 0 24 25" xmlns="http://www.w3.org/2000/svg">
same as above and check icons name '_'

2021-06-11 22:29 UTC, pkarpovich commented on src/components/menu-tabs/icon_menu_dedicated.svg
> +<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
same as above

2021-06-11 22:29 UTC, pkarpovich commented on src/atoms/person/index.js
> +  dangerouslyAllowMutability: true,
remove it

2021-06-11 22:29 UTC, pkarpovich commented on src/components/MainLayout.js
> +    overflow-y: scroll;
auto

2021-06-11 22:29 UTC, pkarpovich commented on src/components/menu-tabs/index.js
> +        <Img>
Box

2021-06-17 13:06 UTC, R00BEL commented on src/components/MenuLayout.js
> +    width: 100%;
fixed

2021-06-17 13:28 UTC, roobel2005 commented on src/components/h1.js
> +  margin-top: ${(props) => props.marginTop ?? "0.67em"};
fixed

2021-06-17 13:29 UTC, roobel2005 commented on src/components/h2.js
> +  padding: ${(props) => props.padding ?? props.p ?? "0"};
fixed

2021-06-17 13:41 UTC, roobel2005 commented on src/components/label.js
> +  padding: ${(props) => props.padding ?? props.p ?? "0"};
fixed

2021-06-20 13:25 UTC, pkarpovich requested changes

2021-06-20 13:25 UTC, pkarpovich commented on package.json
> +    "web-vitals": "^2.0.1",
remove it

2021-06-20 13:25 UTC, pkarpovich commented on src/atoms/personCount/index.js
> +const personCountState = atom({
move into basket atom

2021-06-20 13:25 UTC, pkarpovich commented on src/atoms/basket/index.js
> +  default: [],
change to obj

2021-06-20 13:25 UTC, pkarpovich commented on src/components/MainLayout.js
> -    justify-content: center;
return this line

2021-06-20 13:25 UTC, pkarpovich commented on src/components/dark-mode-switcher/index.js
> +import DarkModeIcon from "../../assets/icons/dark-mode-switcher/dark-mode-symbol.svg";
../../../../

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/components/swipe-delete/index.js
> +      setCandidateForDeletion((candidateForDeletion) => {
onPreRemove

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +  const [candidateForDeletion, setCandidateForDeletion] = useState({
preRemoveItemId

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +  const sum = useMemo(() => {
refactor

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +    (changesTo, indexProducts) => () => {
diff

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +        setProductsInBasketAtoms([
arrow function

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +            count: productsInBasketAtoms[indexProducts].count + changesTo,
...item

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +          ...productsInBasketAtoms.slice(0, indexProducts),
map

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +    if (!disable && productsInBasketAtoms.length) {
isDisabled

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/basket/index.js
> +      fetch(`/api/message/${restaurantId}/${tableId}`, {
async/await

2021-06-20 13:25 UTC, pkarpovich commented on src/pages/menu/expanded-menu/components/navigation/index.js
> +const Navigation = (props) => {
{}

2021-06-24 11:50 UTC, pkarpovich approved these changes

2021-06-24 11:50 UTC, merged